export const data = [
   {
      img: "/images/js.png",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours Sur JavaScript",
      point: "4.20",
      vue: "2",
      auteur: "par Leon Dilan",
      prix: "250$",
      categorie: "progInfo",
   },
   {
      img: "/images/PHP.webp",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours Sur PHP",
      point: "5.00",
      vue: "1",
      auteur: "par Gustave Gautier",
      prix: "250$",
      categorie: "progInfo",
   },
   {
      img: "/images/adobePre.webp",
      descCours: "Cours Sur Adobe Pre",
      imgAuteur: "/images/testimonial-1.png",
      point: "5.00",
      vue: "1",
      auteur: "par John Doe",
      prix: "250$",
      categorie: "infographie",
   },
   {
      img: "/images/adobe-after-effects.jpg",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours  Sur After Effect",
      point: "5.00",
      vue: "1",
      auteur: "par Igor Kollo",
      prix: "250$",
      categorie: "infographie",
   },
   {
      img: "/images/canva.webp",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours  Sur Canvas",
      point: "5.00",
      vue: "1",
      auteur: "par Borel David",
      prix: "250$",
      categorie: "infographie",
   },
   {
      img: "/images/flutter.png",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours  Sur Flutter",
      point: "5.00",
      vue: "1",
      auteur: "par Loic Pierre",
      prix: "250$",
      categorie: "progInfo",
   },
   {
      img: "/images/compta2.jpg",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours  Sur La Comtabilité",
      point: "5.00",
      vue: "1",
      auteur: "par Rudy Nathan",
      prix: "250$",
      categorie: "Compta",
   },
   {
      img: "/images/reseau1.jpg",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours  Reseau Informatique",
      point: "5.00",
      vue: "1",
      auteur: "par Justin Angu",
      prix: "250$",
      categorie: "ReseauInfo",
   },
   {
      img: "/images/react.png",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours Sur React JS",
      point: "5.00",
      vue: "1",
      auteur: "par John Doe",
      prix: "250$",
      categorie: "progInfo",
   },
   {
      img: "/images/react.png",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours Sur NODE JS",
      point: "5.00",
      vue: "1",
      auteur: "par Igor Kollo",
      prix: "250$",
      categorie: "progInfo",
   },
   {
      img: "/images/reactnative.png",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours  Sur React Native",
      point: "5.00",
      vue: "1",
      auteur: "par Borel David",
      prix: "250$",
      categorie: "progInfo",
   },
   {
      img: "/images/laravel.png",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours sur LARAVEL",
      point: "5.00",
      vue: "1",
      auteur: "par Rudy Nathan",
      prix: "250$",
      categorie: "progInfo",
   },
   {
      img: "/images/MongoDB.jpg",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours Sur MONGO DB",
      point: "5.00",
      vue: "1",
      auteur: "par Justin Angu",
      prix: "250$",
      categorie: "progInfo",
   },
  
   

   
   {
      img: "/images/Photoshop.png",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours  Sur PhotoShop",
      point: "5.00",
      vue: "1",
      auteur: "par Igor Kollo",
      prix: "250$",
      categorie: "infographie",
   },
  
 
   {
      img: "/images/compta1.jpg",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours  Sur La Finance",
      point: "4.20",
      vue: "2",
      auteur: "par Leon Dilan",
      prix: "250$",
      categorie: "Compta",
   },
   {
      img: "/images/compta3.jpg",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours Sur Business Affaire",
      point: "5.00",
      vue: "1",
      auteur: "par john Doe",
      prix: "250$",
      categorie: "Compta",
   },
   {
      img: "/images/sage.jfif",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours Sur SAGE SAARI",
      point: "5.00",
      vue: "1",
      auteur: "par Igor Kollo",
      prix: "250$",
      categorie: "Compta",
   },
  
   {
      img: "/images/ccna1.jpg",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours Securité Info..",
      point: "4.20",
      vue: "2",
      auteur: "par Leon Dilan",
      prix: "250$",
      categorie: "ReseauInfo",
   },
   {
      img: "/images/reseau2.jpg",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours Sur le LAN",
      point: "5.00",
      vue: "1",
      auteur: "par John Doe",
      prix: "250$",
      categorie: "ReseauInfo",
   },
   {
      img: "/images/reseau3.jpg",
      imgAuteur: "/images/testimonial-1.png",
      descCours: "Cours Sur CISCO",
      point: "5.00",
      vue: "1",
      auteur: "par Igor Kollo",
      prix: "250$",
      categorie: "ReseauInfo",
   },
];
